# Generated by Django 3.2.13 on 2022-05-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='Priority',
            field=models.CharField(choices=[('Rn', 'Right now'), ('some', 'First'), ('some', 'Second'), ('some', 'Third'), ('some', 'Fourth'), ('some', 'Fifth'), ('some', 'Sixth'), ('some', 'Seventh'), ('some', 'Eighth'), ('some', 'Nineth'), ('some', 'Tenth')], default=('Rn', 'Right now'), max_length=10),
        ),
    ]
