# Generated by Django 3.2.13 on 2022-05-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_goal_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='dead_line',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.CharField(choices=[('Right now', 'Right now'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth'), ('9', 'Nineth'), ('10', 'Tenth')], default=('Right now', 'Right now'), max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(default='In progress', max_length=20),
        ),
    ]
