# Generated by Django 3.2.13 on 2022-05-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_goal_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, help_text='Text your goal here...', max_length=60),
        ),
    ]
